config/routes.rb
Rails.application.routes.draw do
  resources :tropes
  resources :genres
  resources :shows
  resources :actors
  resources :characters
  resources :episodes
  resources :producers, only: [:new, :create, :delete]
  resources :sessions, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/welcome", to: "producers#welcome", as: "welcome"
  get "/profile", to: "producers#show", as: "profile"
  delete "/logout", to: "sessions#destroy"
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :appearances
  has_many :shows, through: :appearances
  has_many :producers, through: :shows



  def costars
    costars = []
    self.shows.each do |show|
      show.actors.each do |actor|
        if actor != self
          costars << actor
        end
      end
    end
    costars
  end

# for api use
  def str_maker
    split = self.name.split(' ')
    split.join('+')
  end

  def pic
    src = GetActors.new.get_pic(self.str_maker)
    src["items"][0]["pagemap"]["cse_image"][0]["src"]
  end


  # has_many :starring_appearances, class_name: "Coappearance", foreign_key: "star_id"
  # has_many :costarring_appearances, class_name: "Coappearance", foreign_key: "costar_id"
  # has_many :costars, through: :starring_appearances, source: :costar
end

app/models/appearance.rb
class Appearance < ApplicationRecord
  belongs_to :actor
  belongs_to :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :tropes
end

app/models/get_actors.rb
# JSON API to get actor pic
require 'json'
require 'net/http'
require 'net/https'

class GetActors

  def get_pic(str)
    url = "https://www.googleapis.com/customsearch/v1?q=#{str}&cx=014219253890378238536:7qwucubk_mm&key=AIzaSyBeTOwI9eto5dEpQ3oUlRPCIvtS1TvS3kU"
    uri = URI.parse(url)
    response = Net::HTTP.get_response(uri)
    JSON.parse(response.body)
  end

end

app/models/producer.rb
class Producer < ApplicationRecord
  has_secure_password
  has_many :shows
  has_many :actors, through: :shows

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :influencer, class_name: "Show"
  belongs_to :influenced, class_name:"Show"
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :producer
  has_many :appearances
  has_many :actors, through: :appearances
  belongs_to :genre
  has_many :show_tropes
  has_many :tropes, through: :show_tropes

  has_many :influencing_relationships, class_name: "Relationship", foreign_key: "influencer_id"
  has_many :influenced_relationships, class_name: "Relationship", foreign_key: "influenced_id"
  has_many :influences, through: :influenced_relationships, source: :influencer
  has_many :influenced, through: :influencing_relationships, source: :influenced

end

app/models/show_trope.rb
class ShowTrope < ActiveRecord::Base
belongs_to :show
belongs_to :trope 


end

app/models/trope.rb
class Trope < ApplicationRecord
  belongs_to :genre
  has_many :show_tropes
  has_many :shows, through: :show_tropes
  has_many :actors, through: :show
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @actors = Actor.all
    render :index
  end

  def update

    @actor = Actor.find(params[:id])
    if @actor.update(actor_params)
      redirect_to #TODO
    else
      render #TODO
    end
  end

  def show
    @actor = Actor.find(params[:id])
    @reviews = ["#{@actor.name} is spellbinding in #{@actor.shows.sample.title}", "#{@actor.name} gives the performance of a lifetime in #{@actor.shows.sample.title}", "#{@actor.name} is back with a vengeance", "#{@actor.shows.sample.title} is the best #{@actor.name}'s been in years", "Mark my words: #{@actor.shows.sample.title} is the beginning of the #{@actor.name}aissance", "#{@actor.name} is sure to win a Daytime Emmy for #{@actor.shows.sample.title}", "#{@actor.name} sneaks up on you and floors you in #{@actor.shows.sample.title}", "#{@actor.name}. Is. Back.", "If you're not watching #{@actor.name} in #{@actor.shows.sample.title}, what are you even doing?", "One word for #{@actor.name}'s most recent performance: Superb", "If there's a stronger shoe-in for an Emmy than #{@actor.name} in #{@actor.shows.sample.title}, I don't know who it is", "#{@actor.name} is jaw-dropping", "Get ready for the return of #{@actor.name} to the A-list", "#{@actor.shows.sample.title} is the hit show of the summer", "There is no examination of our current moment more vital than #{@actor.shows.sample.title}", "Is #{@actor.name} the hottest thing in Hollywood?", "Watch out, Timothée Chalamet: #{@actor.name} is coming for your crown"]
  end

  private

  def actor_params
    params.require(:actor).permit(:name, :a_list, :characters, :shows, :producers, :episodes)
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.all
  end

  def new
    @show = Show.new
    @show.influencing_relationships.build()
    @show.influencing_relationships.build()
  end

  def create
    @show = Show.create(title: params[:show][:title], genre_id: params[:show][:genre_id], producer: current_producer)
    @influence_one = Show.find(params[:show][:influenced])
    @influence_two = Show.find(params[:show][:influences])


    if @show.save
      Relationship.create(influencer_id: @influence_one.id, influenced_id: @show.id)
      Relationship.create(influencer_id: @influence_two.id, influenced_id: @show.id)
      redirect_to "/shows/#{@show.id}/edit"
    else
      flash[:notice] = "I'm not seeing the whole picture, doll."
      render :new
    end
  end

  def show
    @show = Show.find(params[:id])
  end

  def edit
    @show = Show.find(params[:id])
  end

  def update
    @show = Show.find(params[:id])
    params[:show][:tropes].each do |trope|
      if trope != ""
        ShowTrope.create(trope_id: trope, show_id: @show.id)
      end
    end

    params[:show][:actors].each do |actor|
      if actor != ""
        Appearance.create(actor_id: actor, show_id: @show.id)
      end
    end

    if @show.save
      redirect_to @show
    else
      render :edit
    end
  end

    def destroy
      @show = Show.find(params[:id])
      @show.destroy
    end

private

def show_params
  params.require(:show).permit(:title, :genre, influences:[], actors:[])
end


end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/tropes_helper.rb
module TropesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greenlight</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar  navbar-inverse text-monospace">
       <div class="navbar-class">
         <div class="container">
           <% if session[:logged_in_producer_id] %>
           <ul class="nav">
               <li class="nav-item">
                 <a href="#">
                   <img src="/greenlight-logo.png" alt="logo">
                 </a>
               </li>
               <li class="nav-item">
                 <p class = "nav-link">
                   <%= link_to "LOGOUT", logout_path, method: :delete, id: session[:logged_in_producer_id]  %>
                 </p>
               </li>
               <li class="nav-item">
               <p class="nav-link"> <%= link_to "PROFILE", profile_path(@producer) %></p>
               </li>
               <li class="nav-item">
               <p class="nav-link"><%= link_to "MAKE A NEW SHOW", new_show_path %></p>
               </li>
              <% else %>
              <ul class="nav">
                <li class="nav-item">
                  <a href="#">
                    <img src="/greenlight-logo.png" alt="logo">
                  </a>
                </li>
                <li class="nav-item">
                  <p class="nav-link"><%= link_to "SIGN UP", new_producer_path %></p>
                </li>
                <li>
                    <p class="nav-link"><%= link_to "LOG IN", new_session_path %></p>
                </li>
              </ul>
             <% end %>
           </ul>


         </div>
      </div>
    </header>

    <div style="margin:40px;" class="text-monospace">

    <%= yield %>

    </div>
  </body>
</html>